name: Build and Release Bukkit Plugin


on:
  push:
    branches:
      - master  # 触发动作的分支
  pull_request:
    branches:
      - master

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bukkit-plugin
          path: target/*.jar


  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: bukkit-plugin
          path: target

      - name: Get current pom version of project
        uses: PERES-Richard/maven-get-version-action@v3.0.0

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.pom-version.outputs.version }}
          release_name: Release ${{ steps.pom-version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload JAR file to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/your-plugin.jar
          asset_name: your-plugin.jar
          asset_content_type: application/java-archive
